# Generated by Django 3.0.5 on 2024-01-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitems',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
